import FAQItem from "./FAQItem";

const FAQ = () => {

  const faqs = [
    {
      id: 1,
      question:
        "What is CSE Express?",

      answer:
        "CSE Express is a digital platform where CSE students can access semester-wise previous year questions, AI-assisted solutions and study resources.",
    },

    {
      id: 2,
      question:
        "How can I access PDF resources?",

      answer:
        "After selecting your required semester, you can request access. Once payment is verified, the selected semester resources will be available in your account.",
    },

    {
      id: 3,
      question:
        "Can I purchase only one semester?",

      answer:
        "Yes. You can purchase access for any specific semester according to your requirement.",
    },

    {
      id: 4,
      question:
        "Are the solutions generated by AI?",

      answer:
        "AI is used to assist in creating solutions. All resources are organized and reviewed before publishing.",
    },

    {
      id: 5,
      question:
        "Will new questions be added regularly?",

      answer:
        "Yes. We will continuously add new university questions, solutions and learning resources.",
    },
  ];


  return (
    <section className="py-24">

      <div className="container">

        <div className="text-center max-w-3xl mx-auto">

          <span className="uppercase tracking-[4px] text-blue-600 font-semibold">
            FAQ
          </span>

          <h2 className="text-4xl lg:text-5xl font-bold mt-4">
            Frequently Asked Questions
          </h2>

          <p className="mt-5 text-slate-500 leading-8">
            Find answers to common questions about CSE Express,
            access system and study materials.
          </p>

        </div>


        <div className="max-w-4xl mx-auto mt-14 space-y-5">

          {faqs.map((faq) => (
            <FAQItem
              key={faq.id}
              faq={faq}
            />
          ))}

        </div>


      </div>

    </section>
  );
};

export default FAQ;